### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by kbwestfall** [pypeit/PypeIt#510]
Consolidating a list of test failures here.  These need to be fixed!

test_flux.py
test_fluxspec.py
test_wavecalib.py

The first two have to do with errors in specobjs, and the latter has to do with the arc line parameters.

**Comment by jhennawi** [comment]
I fixed the test_wavecalibs in my current PR. I think @profxj fixed the fluxing tests. So I'd say we are good here, but let's wait to close it.

**Comment by profxj** [comment]
fluxspec is still broken but only because fluxing is (I think).
